const items = [
    {
        id: 1,
        img: "https://m.media-amazon.com/images/I/61yY7B+O5AS._AC_UL320_.jpg",
        name: "Samsung Electronics Galaxy Watch",
        price: 308,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "best_sale",
        oldPrice: 350.00,
        stars: 5,
        color: "black",
        rating: 1000,
    },
    {
        id: 2,
        img: "https://m.media-amazon.com/images/I/61xR1QRzYlL._AC_UL320_.jpg",
        name: "Bulova Modern Quartz Men's Watch",
        price: 405,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "most_popular",
        oldPrice: 350.00,
        stars:4,
        color: "black"
    },
    {
        id: 3,
        img: "https://m.media-amazon.com/images/I/81lfjlFAWcL._AC_UL320_.jpg",
        name: "HUGO Men's Stainless Steel Quartz Watch ",
        price: 71,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "best_sale",
        oldPrice: 350.00,
        stars: 4,
        color: "silver"
    },
    {
        id: 4,
        img: "https://m.media-amazon.com/images/I/61bizIa5XwL._AC_UL320_.jpg",
        name: "Fossil Gen 5 Carlyle Stainless Steel Watch",
        price: 100,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "most_popular",
        oldPrice: 350.00,
        stars: 5,
        color: "black",
        rating: 1000,
    },
    {
        id: 5,
        img: "https://m.media-amazon.com/images/I/71sMS5i3wxL._AC_UL320_.jpg",
        name: "Michael Kors Men's Slim Runway Stainless Steel Quartz Watch",
        price: 189,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "best_sale",
        oldPrice: 350.00,
        stars: 3,
        color: "black"
    },
    {
        id: 6,
        img: "https://m.media-amazon.com/images/I/81KEqfAvWhL._AC_UL320_.jpg",
        name: "Timex Easy Reader 38mm Leather Strap Watch",
        price: 44,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "most_popular",
        oldPrice: 350.00,
        stars: 4,
        color: "black"
    },
    {
        id: 7,
        img: "https://m.media-amazon.com/images/I/61rlZhEPK3L._AC_UL320_.jpg",
        name: "Fossil Men's Machine Stainless Steel Quartz Chronograph Watch",
        price:  85,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "most_popular",
        oldPrice: 350.00,
        stars: 4,
        color: "black"
    },
    {
        id: 8,
        img: "https://m.media-amazon.com/images/I/71YyQ7SNJKL._AC_UL320_.jpg",
        name: "Fossil Men's The Minimalist Recycled Stainless Steel Quartz Chronograph Watch",
        price: 59,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        oldPrice: 350.00,
        stars: 5,
        color: "silver"
    },
    {
        id: 9,
        img: "https://m.media-amazon.com/images/I/71nr0o7oZjS._AC_UL320_.jpg",
        name: "Citizen Eco-Drive Promaster Diver Quartz Men's Watch,",
        price: 262,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        oldPrice: 350.00,
        stars: 2,
        color: "silver"
    },
    {
        id: 10,
        img: "https://m.media-amazon.com/images/I/81E2IhbmPBL._AC_UL320_.jpg",
        name: "Fossil Men's Townsman Stainless Steel and Leather Casual Quartz Chronograph Watch",
        price: 119,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        quality: "best_sale",
        oldPrice: 350.00,
        stars: 3,
        color: "brown"
    },
    {
        id: 11,
        img: "https://m.media-amazon.com/images/I/51f1OG6yHrL._AC_UL320_.jpg",
        name: "Fossil Men's the Minimalist Stainless Steel Slim Casual Quartz Watch",
        price: 39,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        oldPrice: 350.00,
        stars: 1,
        color: "black"
    },
    {
        id: 12,
        img: "https://m.media-amazon.com/images/I/81hU8WSNJeL._AC_UL320_.jpg",
        name: "Fossil Men's Townsman Stainless Steel Mechanical Automatic Watch",
        price: 139,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "men",
        oldPrice: 350.00,
        stars: 5,
        color: "brown"
    },
    {
        id: 13,
        img: "https://m.media-amazon.com/images/I/715rhdkKRLL._AC_UL320_.jpg",
        name: "Michael Kors Pyper Three-Hand Stainless Steel Watch",
        price: 89.99,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        oldPrice: 350.00,
        stars: 5,
        color: "silver"
    },
    {
        id: 14,
        img: "https://m.media-amazon.com/images/I/81IhzW6ilzL._AC_UL320_.jpg",
        name: "Fossil Women's Riley Stainless Steel Crystal-Accented Multifunction Quartz Watch",
        price: 78.73,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        oldPrice: 350.00,
        stars: 4,
        color: "black"
    },
    {
        id: 15,
        img: "https://m.media-amazon.com/images/I/81UJCcC9tpL._AC_UL320_.jpg",
        name: "Michael Kors Women's Lady Nini Chain Watch",
        price: 131.38,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        oldPrice: 350.00,
        stars: 5,
        color: "yellow"
    },
    {
        id: 16,
        img: "https://m.media-amazon.com/images/I/81giIgBedaL._AC_UL320_.jpg",
        name: "Michael Kors Women's Gen 5E 43mm Stainless Steel Touchscreen Smartwatch",
        price: 78.73,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        stars: 3,
        color: "pink",
        rating: 1000,
    },
    {
        id: 17,
        img: "https://m.media-amazon.com/images/I/51GuaHHFaLL._AC_UL320_.jpg",
        name: "Michael Kors Women's Ritz Stainless Steel Watch With Crystal Topring",
        price: 134.71,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        stars: 5,
        color: "silver"
    },
    {
        id: 18,
        img: "https://m.media-amazon.com/images/I/51pQnKnaoNL._AC_UL320_.jpg",
        name: "Fossil Women's Jacqueline Stainless Steel Dress Quartz Watch",
        price: 149,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "women",
        stars: 3,
        color: "silver"
    },{
        id: 19,
        img: "https://m.media-amazon.com/images/I/61AyBdh+-ZL._AC_UL480_FMwebp_QL65_.jpg",
        name: "CakCity Kids Watches Digital Sport Watches for Boys Girls",
        price: 16.99,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "kids",
        stars: 4,
        color: "camo"
    },{
        id: 20,
        img: "https://m.media-amazon.com/images/I/91oFhQaYPoL._AC_UL480_FMwebp_QL65_.jpg",
        name: "Timex Time Machines Digital 35mm Watch",
        price: 22,
        amount: 1,
        desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
        category: "kids",
        stars: 4,
        color: "blue"
    }
    // },{
    //     id: 21,
    //     img: "https://m.media-amazon.com/images/I/61MliEjiBaL._AC_UL480_FMwebp_QL65_.jpg",
    //     name: "CakCity Kids Watches Digital Outdoor Sport Waterproof Electrical EL-Lights Watches",
    //     price: 15.99,
    //     amount: 1,
    //     desc: "Donerton Smart Watch, Fitness Tracker for Android Phones, Fitness Tracker with Heart Rate and Sleep Monitor, Activity Tracker with IP67 Waterproof Pedometer Smartwatch with Step Counter for Women Men",
    //     category: "kids",
    //     stars: 5,
    //     color: "blue"
    // }
]

export default items